2. Contenido:
```yaml
name: Package NuGet
on: push
jobs:
build:
 runs-on: ubuntu-latest
 steps:
   - uses: actions/checkout@v4
   - name: Setup .NET
     uses: actions/setup-dotnet@v4
     with:
       dotnet-version: '8.x'
   - name: Run tests
     run: dotnet test
   - name: Pack NuGet
     run: dotnet pack Bank.Domain/Bank.Domain.csproj -c Release -o out
   - name: Upload NuGet
     uses: actions/upload-artifact@v4
     with:
       name: nuget-package
       path: out/*.nupkg
